from __future__ import annotations

ALLOWED_ENTITY_TYPES: tuple[str, ...] = (
    "疾病",
    "症状",
    "体征",
    "影像学表现",
    "病因",
    "危险因素",
    "检查",
    "检查指标",
    "检查结果",
    "病理改变",
    "发病机制",
    "解剖部位",
    "组织器官",
    "细胞",
    "基因",
    "蛋白",
    "分子通路",
    "治疗",
    "药物",
    "预防措施",
    "并发症",
    "分型分级",
    "流行病学特征",
    "预后",
)

ALLOWED_RELATIONS: tuple[str, ...] = (
    "caused_by",
    "risk_factor",
    "has_symptom",
    "has_sign",
    "has_imaging_feature",
    "diagnosed_by",
    "has_test_indicator",
    "has_test_result",
    "has_pathological_change",
    "involves_mechanism",
    "involves_pathway",
    "affects_organ",
    "affects_cell",
    "associated_gene",
    "associated_protein",
    "treated_by",
    "prevented_by",
    "has_complication",
    "has_classification",
    "has_epidemiology",
    "has_prognosis",
    "differential_diagnosis",
)

ALLOWED_RELATION_SET = frozenset(ALLOWED_RELATIONS)
